QT += xml widgets concurrent

TARGET        = $$qtLibraryTarget(scg)
TEMPLATE      = lib
INCLUDEPATH  += ../../kbe \
                ./
INCLUDEPATH  += editor/runtime/src/

DESTDIR = ../../bin/plugins

CONFIG       += plugin

OBJECTS_DIR = obj
MOC_DIR = moc

RESOURCES     = scg.qrc

win32 {
    DEFINES += _USE_MATH_DEFINES
}

HEADERS += \
    editor/runtime/antlrcpp-ios/antlrcpp_ios.h \
    editor/runtime/src/ANTLRErrorListener.h \
    editor/runtime/src/ANTLRErrorStrategy.h \
    editor/runtime/src/ANTLRFileStream.h \
    editor/runtime/src/ANTLRInputStream.h \
    editor/runtime/src/BailErrorStrategy.h \
    editor/runtime/src/BaseErrorListener.h \
    editor/runtime/src/BufferedTokenStream.h \
    editor/runtime/src/CharStream.h \
    editor/runtime/src/CommonToken.h \
    editor/runtime/src/CommonTokenFactory.h \
    editor/runtime/src/CommonTokenStream.h \
    editor/runtime/src/ConsoleErrorListener.h \
    editor/runtime/src/DefaultErrorStrategy.h \
    editor/runtime/src/DiagnosticErrorListener.h \
    editor/runtime/src/Exceptions.h \
    editor/runtime/src/FailedPredicateException.h \
    editor/runtime/src/InputMismatchException.h \
    editor/runtime/src/IntStream.h \
    editor/runtime/src/InterpreterRuleContext.h \
    editor/runtime/src/Lexer.h \
    editor/runtime/src/LexerInterpreter.h \
    editor/runtime/src/LexerNoViableAltException.h \
    editor/runtime/src/ListTokenSource.h \
    editor/runtime/src/NoViableAltException.h \
    editor/runtime/src/Parser.h \
    editor/runtime/src/ParserInterpreter.h \
    editor/runtime/src/ParserRuleContext.h \
    editor/runtime/src/ProxyErrorListener.h \
    editor/runtime/src/RecognitionException.h \
    editor/runtime/src/Recognizer.h \
    editor/runtime/src/RuleContext.h \
    editor/runtime/src/RuleContextWithAltNum.h \
    editor/runtime/src/RuntimeMetaData.h \
    editor/runtime/src/Token.h \
    editor/runtime/src/TokenFactory.h \
    editor/runtime/src/TokenSource.h \
    editor/runtime/src/TokenStream.h \
    editor/runtime/src/TokenStreamRewriter.h \
    editor/runtime/src/UnbufferedCharStream.h \
    editor/runtime/src/UnbufferedTokenStream.h \
    editor/runtime/src/Vocabulary.h \
    editor/runtime/src/WritableToken.h \
    editor/runtime/src/antlr4-common.h \
    editor/runtime/src/antlr4-runtime.h \
    editor/runtime/src/atn/ATN.h \
    editor/runtime/src/atn/ATNConfig.h \
    editor/runtime/src/atn/ATNConfigSet.h \
    editor/runtime/src/atn/ATNDeserializationOptions.h \
    editor/runtime/src/atn/ATNDeserializer.h \
    editor/runtime/src/atn/ATNSerializer.h \
    editor/runtime/src/atn/ATNSimulator.h \
    editor/runtime/src/atn/ATNState.h \
    editor/runtime/src/atn/ATNType.h \
    editor/runtime/src/atn/AbstractPredicateTransition.h \
    editor/runtime/src/atn/ActionTransition.h \
    editor/runtime/src/atn/AmbiguityInfo.h \
    editor/runtime/src/atn/ArrayPredictionContext.h \
    editor/runtime/src/atn/AtomTransition.h \
    editor/runtime/src/atn/BasicBlockStartState.h \
    editor/runtime/src/atn/BasicState.h \
    editor/runtime/src/atn/BlockEndState.h \
    editor/runtime/src/atn/BlockStartState.h \
    editor/runtime/src/atn/ContextSensitivityInfo.h \
    editor/runtime/src/atn/DecisionEventInfo.h \
    editor/runtime/src/atn/DecisionInfo.h \
    editor/runtime/src/atn/DecisionState.h \
    editor/runtime/src/atn/EmptyPredictionContext.h \
    editor/runtime/src/atn/EpsilonTransition.h \
    editor/runtime/src/atn/ErrorInfo.h \
    editor/runtime/src/atn/LL1Analyzer.h \
    editor/runtime/src/atn/LexerATNConfig.h \
    editor/runtime/src/atn/LexerATNSimulator.h \
    editor/runtime/src/atn/LexerAction.h \
    editor/runtime/src/atn/LexerActionExecutor.h \
    editor/runtime/src/atn/LexerActionType.h \
    editor/runtime/src/atn/LexerChannelAction.h \
    editor/runtime/src/atn/LexerCustomAction.h \
    editor/runtime/src/atn/LexerIndexedCustomAction.h \
    editor/runtime/src/atn/LexerModeAction.h \
    editor/runtime/src/atn/LexerMoreAction.h \
    editor/runtime/src/atn/LexerPopModeAction.h \
    editor/runtime/src/atn/LexerPushModeAction.h \
    editor/runtime/src/atn/LexerSkipAction.h \
    editor/runtime/src/atn/LexerTypeAction.h \
    editor/runtime/src/atn/LookaheadEventInfo.h \
    editor/runtime/src/atn/LoopEndState.h \
    editor/runtime/src/atn/NotSetTransition.h \
    editor/runtime/src/atn/OrderedATNConfigSet.h \
    editor/runtime/src/atn/ParseInfo.h \
    editor/runtime/src/atn/ParserATNSimulator.h \
    editor/runtime/src/atn/PlusBlockStartState.h \
    editor/runtime/src/atn/PlusLoopbackState.h \
    editor/runtime/src/atn/PrecedencePredicateTransition.h \
    editor/runtime/src/atn/PredicateEvalInfo.h \
    editor/runtime/src/atn/PredicateTransition.h \
    editor/runtime/src/atn/PredictionContext.h \
    editor/runtime/src/atn/PredictionMode.h \
    editor/runtime/src/atn/ProfilingATNSimulator.h \
    editor/runtime/src/atn/RangeTransition.h \
    editor/runtime/src/atn/RuleStartState.h \
    editor/runtime/src/atn/RuleStopState.h \
    editor/runtime/src/atn/RuleTransition.h \
    editor/runtime/src/atn/SemanticContext.h \
    editor/runtime/src/atn/SetTransition.h \
    editor/runtime/src/atn/SingletonPredictionContext.h \
    editor/runtime/src/atn/StarBlockStartState.h \
    editor/runtime/src/atn/StarLoopEntryState.h \
    editor/runtime/src/atn/StarLoopbackState.h \
    editor/runtime/src/atn/TokensStartState.h \
    editor/runtime/src/atn/Transition.h \
    editor/runtime/src/atn/WildcardTransition.h \
    editor/runtime/src/dfa/DFA.h \
    editor/runtime/src/dfa/DFASerializer.h \
    editor/runtime/src/dfa/DFAState.h \
    editor/runtime/src/dfa/LexerDFASerializer.h \
    editor/runtime/src/misc/InterpreterDataReader.h \
    editor/runtime/src/misc/Interval.h \
    editor/runtime/src/misc/IntervalSet.h \
    editor/runtime/src/misc/MurmurHash.h \
    editor/runtime/src/misc/Predicate.h \
    editor/runtime/src/support/Any.h \
    editor/runtime/src/support/Arrays.h \
    editor/runtime/src/support/BitSet.h \
    editor/runtime/src/support/CPPUtils.h \
    editor/runtime/src/support/Declarations.h \
    editor/runtime/src/support/StringUtils.h \
    editor/runtime/src/support/guid.h \
    editor/runtime/src/tree/AbstractParseTreeVisitor.h \
    editor/runtime/src/tree/ErrorNode.h \
    editor/runtime/src/tree/ErrorNodeImpl.h \
    editor/runtime/src/tree/IterativeParseTreeWalker.h \
    editor/runtime/src/tree/ParseTree.h \
    editor/runtime/src/tree/ParseTreeListener.h \
    editor/runtime/src/tree/ParseTreeProperty.h \
    editor/runtime/src/tree/ParseTreeVisitor.h \
    editor/runtime/src/tree/ParseTreeWalker.h \
    editor/runtime/src/tree/TerminalNode.h \
    editor/runtime/src/tree/TerminalNodeImpl.h \
    editor/runtime/src/tree/Trees.h \
    editor/runtime/src/tree/pattern/Chunk.h \
    editor/runtime/src/tree/pattern/ParseTreeMatch.h \
    editor/runtime/src/tree/pattern/ParseTreePattern.h \
    editor/runtime/src/tree/pattern/ParseTreePatternMatcher.h \
    editor/runtime/src/tree/pattern/RuleTagToken.h \
    editor/runtime/src/tree/pattern/TagChunk.h \
    editor/runtime/src/tree/pattern/TextChunk.h \
    editor/runtime/src/tree/pattern/TokenTagToken.h \
    editor/runtime/src/tree/xpath/XPath.h \
    editor/runtime/src/tree/xpath/XPathElement.h \
    editor/runtime/src/tree/xpath/XPathLexer.h \
    editor/runtime/src/tree/xpath/XPathLexerErrorListener.h \
    editor/runtime/src/tree/xpath/XPathRuleAnywhereElement.h \
    editor/runtime/src/tree/xpath/XPathRuleElement.h \
    editor/runtime/src/tree/xpath/XPathTokenAnywhereElement.h \
    editor/runtime/src/tree/xpath/XPathTokenElement.h \
    editor/runtime/src/tree/xpath/XPathWildcardAnywhereElement.h \
    editor/runtime/src/tree/xpath/XPathWildcardElement.h \
    editor/scgeditorhelper.h \
    editor/scgfileloader.h \
    editor/scgfilewriter.h \
    editor/scgobjectinforeader.h \
    editor/scgstreamwriter.h \
    editor/scs/sc-memory/sc_type.hpp \
    editor/scs/sc-memory/sc_types.h \
    editor/scs/scs.g4 \
    editor/scs/scsLexer.h \
    editor/scs/scsParser.h \
    editor/scs/scs_parser.hpp \
    editor/scs/scs_types.hpp \
    scgwindow.h \
    scgview.h \
    scgtemplateobjectbuilder.h \
    scgscene.h \
    scgpointobject.h \
    scgpair.h \
    scgobjectsinfodata.h \
    scgobjectsinfo.h \
    scgobject.h \
    scgnode.h \
    scgminimap.h \
    scglayoutmanager.h \
    scgfilewriterimage.h \
    scgdefaultobjectbuilder.h \
    scgcontour.h \
    scgcontentviewer.h \
    scgcontentstring.h \
    scgcontentnumeric.h \
    scgcontentimage.h \
    scgcontentfactory.h \
    scgcontentdialog.h \
    scgcontentchangedialog.h \
    scgcontent.h \
    scgconfig.h \
    scgbus.h \
    scgalphabet.h \
    scgabstractobjectbuilder.h \
    scgpointgraphicsitem.h \
    scgtextitem.h \
    gwf/gwfstreamwriter.h \
    gwf/gwfobjectinforeader.h \
    gwf/gwffilewriter.h \
    gwf/gwffileloader.h \
    scgplugin.h \
    scgfindwidget.h \
    scgundoviewmodel.h \
    scgundoview.h \
    commands/scgcommandselectedobjectmove.h \
    commands/scgcommandpointschange.h \
    commands/scgcommandpointmove.h \
    commands/scgcommandobjectmove.h \
    commands/scgcommandobjectdelete.h \
    commands/scgcommandinsert.h \
    commands/scgcommanddeletecontour.h \
    commands/scgcommandcreatepair.h \
    commands/scgcommandcreatenode.h \
    commands/scgcommandcreatecontour.h \
    commands/scgcommandcreatebus.h \
    commands/scgcommandcontentvisibility.h \
    commands/scgcommandcontentchange.h \
    commands/scgcommandclone.h \
    commands/scgcommandchangeincedentobject.h \
    commands/scgbasecommand.h \
    commands/scgcommandidtfmove.h \
    commands/scgcommandobjectidtfchange.h \
    commands/scgcommandobjecttypechange.h \
    scgexportimage.h \
    arrangers/scgarrangervertical.h \
    arrangers/scgarrangertuple.h \
    arrangers/scgarrangerhorizontal.h \
    arrangers/scgarrangergrid.h \
    arrangers/scgarranger.h \
    select/scgselectinputoutput.h \
    select/scgselect.h \
    select/scgselectsubgraph.h \
    modes/scgselectmode.h \
    modes/scgpairmode.h \
    modes/scgmode.h \
    modes/scginsertmode.h \
    modes/scgcontourmode.h \
    modes/scgclonemode.h \
    modes/scgbusmode.h \
    commands/scgcommandswappairorient.h \
    commands/scgcommandremovebreakpoints.h \
    commands/scgcommandminimizecontour.h \
    scgnodetextitem.h \
    scgtypedialog.h

SOURCES += \
    editor/runtime/src/ANTLRErrorListener.cpp \
    editor/runtime/src/ANTLRErrorStrategy.cpp \
    editor/runtime/src/ANTLRFileStream.cpp \
    editor/runtime/src/ANTLRInputStream.cpp \
    editor/runtime/src/BailErrorStrategy.cpp \
    editor/runtime/src/BaseErrorListener.cpp \
    editor/runtime/src/BufferedTokenStream.cpp \
    editor/runtime/src/CharStream.cpp \
    editor/runtime/src/CommonToken.cpp \
    editor/runtime/src/CommonTokenFactory.cpp \
    editor/runtime/src/CommonTokenStream.cpp \
    editor/runtime/src/ConsoleErrorListener.cpp \
    editor/runtime/src/DefaultErrorStrategy.cpp \
    editor/runtime/src/DiagnosticErrorListener.cpp \
    editor/runtime/src/Exceptions.cpp \
    editor/runtime/src/FailedPredicateException.cpp \
    editor/runtime/src/InputMismatchException.cpp \
    editor/runtime/src/IntStream.cpp \
    editor/runtime/src/InterpreterRuleContext.cpp \
    editor/runtime/src/Lexer.cpp \
    editor/runtime/src/LexerInterpreter.cpp \
    editor/runtime/src/LexerNoViableAltException.cpp \
    editor/runtime/src/ListTokenSource.cpp \
    editor/runtime/src/NoViableAltException.cpp \
    editor/runtime/src/Parser.cpp \
    editor/runtime/src/ParserInterpreter.cpp \
    editor/runtime/src/ParserRuleContext.cpp \
    editor/runtime/src/ProxyErrorListener.cpp \
    editor/runtime/src/RecognitionException.cpp \
    editor/runtime/src/Recognizer.cpp \
    editor/runtime/src/RuleContext.cpp \
    editor/runtime/src/RuleContextWithAltNum.cpp \
    editor/runtime/src/RuntimeMetaData.cpp \
    editor/runtime/src/Token.cpp \
    editor/runtime/src/TokenSource.cpp \
    editor/runtime/src/TokenStream.cpp \
    editor/runtime/src/TokenStreamRewriter.cpp \
    editor/runtime/src/UnbufferedCharStream.cpp \
    editor/runtime/src/UnbufferedTokenStream.cpp \
    editor/runtime/src/Vocabulary.cpp \
    editor/runtime/src/WritableToken.cpp \
    editor/runtime/src/atn/ATN.cpp \
    editor/runtime/src/atn/ATNConfig.cpp \
    editor/runtime/src/atn/ATNConfigSet.cpp \
    editor/runtime/src/atn/ATNDeserializationOptions.cpp \
    editor/runtime/src/atn/ATNDeserializer.cpp \
    editor/runtime/src/atn/ATNSerializer.cpp \
    editor/runtime/src/atn/ATNSimulator.cpp \
    editor/runtime/src/atn/ATNState.cpp \
    editor/runtime/src/atn/AbstractPredicateTransition.cpp \
    editor/runtime/src/atn/ActionTransition.cpp \
    editor/runtime/src/atn/AmbiguityInfo.cpp \
    editor/runtime/src/atn/ArrayPredictionContext.cpp \
    editor/runtime/src/atn/AtomTransition.cpp \
    editor/runtime/src/atn/BasicBlockStartState.cpp \
    editor/runtime/src/atn/BasicState.cpp \
    editor/runtime/src/atn/BlockEndState.cpp \
    editor/runtime/src/atn/BlockStartState.cpp \
    editor/runtime/src/atn/ContextSensitivityInfo.cpp \
    editor/runtime/src/atn/DecisionEventInfo.cpp \
    editor/runtime/src/atn/DecisionInfo.cpp \
    editor/runtime/src/atn/DecisionState.cpp \
    editor/runtime/src/atn/EmptyPredictionContext.cpp \
    editor/runtime/src/atn/EpsilonTransition.cpp \
    editor/runtime/src/atn/ErrorInfo.cpp \
    editor/runtime/src/atn/LL1Analyzer.cpp \
    editor/runtime/src/atn/LexerATNConfig.cpp \
    editor/runtime/src/atn/LexerATNSimulator.cpp \
    editor/runtime/src/atn/LexerAction.cpp \
    editor/runtime/src/atn/LexerActionExecutor.cpp \
    editor/runtime/src/atn/LexerChannelAction.cpp \
    editor/runtime/src/atn/LexerCustomAction.cpp \
    editor/runtime/src/atn/LexerIndexedCustomAction.cpp \
    editor/runtime/src/atn/LexerModeAction.cpp \
    editor/runtime/src/atn/LexerMoreAction.cpp \
    editor/runtime/src/atn/LexerPopModeAction.cpp \
    editor/runtime/src/atn/LexerPushModeAction.cpp \
    editor/runtime/src/atn/LexerSkipAction.cpp \
    editor/runtime/src/atn/LexerTypeAction.cpp \
    editor/runtime/src/atn/LookaheadEventInfo.cpp \
    editor/runtime/src/atn/LoopEndState.cpp \
    editor/runtime/src/atn/NotSetTransition.cpp \
    editor/runtime/src/atn/OrderedATNConfigSet.cpp \
    editor/runtime/src/atn/ParseInfo.cpp \
    editor/runtime/src/atn/ParserATNSimulator.cpp \
    editor/runtime/src/atn/PlusBlockStartState.cpp \
    editor/runtime/src/atn/PlusLoopbackState.cpp \
    editor/runtime/src/atn/PrecedencePredicateTransition.cpp \
    editor/runtime/src/atn/PredicateEvalInfo.cpp \
    editor/runtime/src/atn/PredicateTransition.cpp \
    editor/runtime/src/atn/PredictionContext.cpp \
    editor/runtime/src/atn/PredictionMode.cpp \
    editor/runtime/src/atn/ProfilingATNSimulator.cpp \
    editor/runtime/src/atn/RangeTransition.cpp \
    editor/runtime/src/atn/RuleStartState.cpp \
    editor/runtime/src/atn/RuleStopState.cpp \
    editor/runtime/src/atn/RuleTransition.cpp \
    editor/runtime/src/atn/SemanticContext.cpp \
    editor/runtime/src/atn/SetTransition.cpp \
    editor/runtime/src/atn/SingletonPredictionContext.cpp \
    editor/runtime/src/atn/StarBlockStartState.cpp \
    editor/runtime/src/atn/StarLoopEntryState.cpp \
    editor/runtime/src/atn/StarLoopbackState.cpp \
    editor/runtime/src/atn/TokensStartState.cpp \
    editor/runtime/src/atn/Transition.cpp \
    editor/runtime/src/atn/WildcardTransition.cpp \
    editor/runtime/src/dfa/DFA.cpp \
    editor/runtime/src/dfa/DFASerializer.cpp \
    editor/runtime/src/dfa/DFAState.cpp \
    editor/runtime/src/dfa/LexerDFASerializer.cpp \
    editor/runtime/src/misc/InterpreterDataReader.cpp \
    editor/runtime/src/misc/Interval.cpp \
    editor/runtime/src/misc/IntervalSet.cpp \
    editor/runtime/src/misc/MurmurHash.cpp \
    editor/runtime/src/misc/Predicate.cpp \
    editor/runtime/src/support/Any.cpp \
    editor/runtime/src/support/Arrays.cpp \
    editor/runtime/src/support/CPPUtils.cpp \
    editor/runtime/src/support/StringUtils.cpp \
    editor/runtime/src/support/guid.cpp \
    editor/runtime/src/tree/ErrorNode.cpp \
    editor/runtime/src/tree/ErrorNodeImpl.cpp \
    editor/runtime/src/tree/IterativeParseTreeWalker.cpp \
    editor/runtime/src/tree/ParseTree.cpp \
    editor/runtime/src/tree/ParseTreeListener.cpp \
    editor/runtime/src/tree/ParseTreeVisitor.cpp \
    editor/runtime/src/tree/ParseTreeWalker.cpp \
    editor/runtime/src/tree/TerminalNode.cpp \
    editor/runtime/src/tree/TerminalNodeImpl.cpp \
    editor/runtime/src/tree/Trees.cpp \
    editor/runtime/src/tree/pattern/Chunk.cpp \
    editor/runtime/src/tree/pattern/ParseTreeMatch.cpp \
    editor/runtime/src/tree/pattern/ParseTreePattern.cpp \
    editor/runtime/src/tree/pattern/ParseTreePatternMatcher.cpp \
    editor/runtime/src/tree/pattern/RuleTagToken.cpp \
    editor/runtime/src/tree/pattern/TagChunk.cpp \
    editor/runtime/src/tree/pattern/TextChunk.cpp \
    editor/runtime/src/tree/pattern/TokenTagToken.cpp \
    editor/runtime/src/tree/xpath/XPath.cpp \
    editor/runtime/src/tree/xpath/XPathElement.cpp \
    editor/runtime/src/tree/xpath/XPathLexer.cpp \
    editor/runtime/src/tree/xpath/XPathLexerErrorListener.cpp \
    editor/runtime/src/tree/xpath/XPathRuleAnywhereElement.cpp \
    editor/runtime/src/tree/xpath/XPathRuleElement.cpp \
    editor/runtime/src/tree/xpath/XPathTokenAnywhereElement.cpp \
    editor/runtime/src/tree/xpath/XPathTokenElement.cpp \
    editor/runtime/src/tree/xpath/XPathWildcardAnywhereElement.cpp \
    editor/runtime/src/tree/xpath/XPathWildcardElement.cpp \
    editor/scgeditorhelper.cpp \
    editor/scgfileloader.cpp \
    editor/scgfilewriter.cpp \
    editor/scgobjectinforeader.cpp \
    editor/scgstreamwriter.cpp \
    editor/scs/sc-memory/sc_type.cpp \
    editor/scs/scsLexer.cpp \
    editor/scs/scsParser.cpp \
    editor/scs/scs_parser.cpp \
    editor/scs/scs_types.cpp \
    scgwindow.cpp \
    scgview.cpp \
    scgtemplateobjectbuilder.cpp \
    scgscene.cpp \
    scgpointobject.cpp \
    scgpair.cpp \
    scgobjectsinfodata.cpp \
    scgobjectsinfo.cpp \
    scgobject.cpp \
    scgnode.cpp \
    scgminimap.cpp \
    scglayoutmanager.cpp \
    scgfilewriterimage.cpp \
    scgdefaultobjectbuilder.cpp \
    scgcontour.cpp \
    scgcontentviewer.cpp \
    scgcontentstring.cpp \
    scgcontentnumeric.cpp \
    scgcontentimage.cpp \
    scgcontentfactory.cpp \
    scgcontentdialog.cpp \
    scgcontentchangedialog.cpp \
    scgcontent.cpp \
    scgconfig.cpp \
    scgbus.cpp \
    scgalphabet.cpp \
    scgabstractobjectbuilder.cpp \
    scgpointgraphicsitem.cpp \
    scgtextitem.cpp \
    gwf/gwfstreamwriter.cpp \
    gwf/gwfobjectinforeader.cpp \
    gwf/gwffilewriter.cpp \
    gwf/gwffileloader.cpp \
    scgplugin.cpp \
    scgfindwidget.cpp \
    scgundoviewmodel.cpp \
    scgundoview.cpp \
    commands/scgcommandselectedobjectmove.cpp \
    commands/scgcommandpointschange.cpp \
    commands/scgcommandpointmove.cpp \
    commands/scgcommandobjectmove.cpp \
    commands/scgcommandobjectdelete.cpp \
    commands/scgcommandinsert.cpp \
    commands/scgcommanddeletecontour.cpp \
    commands/scgcommandcreatepair.cpp \
    commands/scgcommandcreatecontour.cpp \
    commands/scgcommandcreatebus.cpp \
    commands/scgcommandcontentvisibility.cpp \
    commands/scgcommandcontentchange.cpp \
    commands/scgcommandclone.cpp \
    commands/scgcommandchangeincedentobject.cpp \
    commands/scgbasecommand.cpp \
    commands/scgcommandcreatenode.cpp \
    commands/scgcommandidtfmove.cpp \
    commands/scgcommandobjectidtfchange.cpp \
    commands/scgcommandobjecttypechange.cpp \
    scgexportimage.cpp \
    arrangers/scgarrangervertical.cpp \
    arrangers/scgarrangertuple.cpp \
    arrangers/scgarrangerhorizontal.cpp \
    arrangers/scgarrangergrid.cpp \
    arrangers/scgarranger.cpp \
    select/scgselectinputoutput.cpp \
    select/scgselect.cpp \
    select/scgselectsubgraph.cpp \
    modes/scgselectmode.cpp \
    modes/scgpairmode.cpp \
    modes/scgmode.cpp \
    modes/scginsertmode.cpp \
    modes/scgcontourmode.cpp \
    modes/scgclonemode.cpp \
    modes/scgbusmode.cpp \
    commands/scgcommandswappairorient.cpp \
    commands/scgcommandremovebreakpoints.cpp \
    commands/scgcommandminimizecontour.cpp \
    scgnodetextitem.cpp \
    scgtypedialog.cpp

TRANSLATIONS += media/translations/scg_en_EN.ts \
                media/translations/scg_ru_RU.ts

lrelease.input         = TRANSLATIONS
lrelease.output        = ${QMAKE_FILE_IN_PATH}/${QMAKE_FILE_IN_BASE}.qm
lrelease.commands      = $$[QT_INSTALL_BINS]/lrelease ${QMAKE_FILE_IN} -qm ${QMAKE_FILE_IN_PATH}/${QMAKE_FILE_IN_BASE}.qm
lrelease.CONFIG       += no_link target_predeps
QMAKE_EXTRA_COMPILERS += lrelease

OTHER_FILES += \
    scgplugin.json

DISTFILES += \
    editor/runtime/CMakeLists.txt \
    editor/runtime/antlr4cpp-vs2013.vcxproj \
    editor/runtime/antlr4cpp-vs2013.vcxproj.filters \
    editor/runtime/antlr4cpp-vs2015.vcxproj \
    editor/runtime/antlr4cpp-vs2015.vcxproj.filters \
    editor/runtime/antlr4cpp-vs2017.vcxproj \
    editor/runtime/antlr4cpp-vs2017.vcxproj.filters \
    editor/runtime/antlrcpp-ios/Info.plist \
    editor/runtime/antlrcpp.xcodeproj/project.pbxproj \
    editor/runtime/antlrcpp.xcodeproj/project.xcworkspace/contents.xcworkspacedata \
    editor/runtime/antlrcpp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist \
    editor/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4.xcscheme \
    editor/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4_ios.xcscheme \
    editor/runtime/antlrcpp.xcodeproj/xcshareddata/xcschemes/antlr4_static.xcscheme \
    editor/runtime/src/tree/xpath/XPathLexer.g4 \
    editor/runtime/src/tree/xpath/XPathLexer.tokens \
    editor/scs/scs.interp \
    editor/scs/scs.tokens \
    editor/scs/scsLexer.interp \
    editor/scs/scsLexer.tokens
